### ISSUE TITLE
Log4j problems with Rundeck 1.6

### ISSUE THREAD

**Issue by solounaletra** [rundeck-plugins/rundeck-ec2-nodes-plugin#9]
Hi. After an upgrade to 1.6 the plugin is no longer working and everytime I try to list nodes I get this error 

```
Class org.apache.commons.logging.impl.Log4JLogger does not implement Log
```

After doing some research it seems to be related to  https://github.com/dtolabs/rundeck/issues/419.
Rollbacking to Rundeck 1.5 fixes the problem
